#!/usr/bin/env bash

AWS_CONFIG_FILE=${AWS_CONFIG_FILE:-"$HOME/.aws/config"} 

usage() {
  echo "Usage: source $0 [SEARCH]"
  echo "A script that selects an AWS profile"
  echo "SEARCH does a fuzzy match on the profile name"
  exit 1
}

check_dependencies() {
    if ! grep --version | grep -q 'GNU grep' 
    then
        echo "Please use GNU grep. brew install grep"
        return 1
    fi
}

check_sourced() {
    [[ -n $ZSH_EVAL_CONTEXT && $ZSH_EVAL_CONTEXT =~ :file$ ]] || [ "$0" != "${BASH_SOURCE[0]}" ] && sourced=1 || sourced=0
    if [ $sourced -eq 0 ]; then
        echo "Please source not execute this script"
        usage
    fi
}

select_profile() {
    local search=$1
    local inner_regex
    local regex
    if [ -n "$search" ]; then
        inner_regex="${search}.*"
    fi
    
    echo "Fetching profiles from $AWS_CONFIG_FILE"

    regex="(?<=^\[profile )(.*${inner_regex})(?=\])"
    profiles=()
    while IFS='' read -r line; do profiles+=("$line"); done < <(grep -oP "$regex" "$AWS_CONFIG_FILE")
   
    select profile in  "${profiles[@]}"
    do
        echo "You have selected $profile"
        export AWS_PROFILE="$profile"
        break
    done
}

check_sourced
check_dependencies || return
select_profile "$1"
